### ISSUE TITLE
upgrade readme file

### ISSUE THREAD

**Issue by Bunkermaster** [Bunkermaster/demo-pmd#1]
- [x] Put some swag in it
- [x] Add a "little something extra"

**Comment by Sereyvuthc** [comment]
You're so amazin !

**Comment by Sereyvuthc** [comment]
Oh my god, you're so amazing !

**Comment by XavierTrs** [comment]
loving it

**Comment by Bunkermaster** [comment]
:trollface:

**Comment by brianbontems** [comment]
🦄

**Comment by Gaudriol** [comment]
🏩

**Comment by CGaulier** [comment]
( ͡° ͜ʖ ͡°).

**Comment by Lawl0x** [comment]
J'adore

**Comment by CGaulier** [comment]
https://codepen.io/PicturElements/full/XaqdRd/ '3'

**Comment by TaySai** [comment]
🐠

**Comment by Bunkermaster** [comment]
# weeeee
lol

**Comment by BiHeyBiWhy** [comment]
![qw1m1uvo](https://user-images.githubusercontent.com/33153966/32110410-c08abcb2-bb37-11e7-986e-9365e5256f6a.jpg)
